using MBC.Shared;

namespace MBC.Core.Events
{
    /// <summary>
    /// Provides information about a <see cref="ControllerRegister"/> that had taken too long to return from
    /// a method call in its associating <see cref="Controller"/>.
    /// </summary>
    public class ControllerTimeoutEvent : ControllerEvent
    {
        private int time;
        private string methodName;

        /// <summary>
        /// Stores the information provided by the <paramref name="exception"/> and bases the <see cref="Event.Message"/>
        /// from it.
        /// </summary>
        /// <param name="exception">The <see cref="ControllerTimeoutException"/> generated by a <see cref="ControllerUser"/>.</param>
        public ControllerTimeoutEvent(ControllerTimeoutException exception)
            : base(exception.Register)
        {
            Init(exception.Register, exception.TimeTaken, exception.MethodName);
        }

        private void Init(ControllerRegister register, int time, string method)
        {
            this.time = time;
            this.methodName = method;

            message = register + " went over the time limit of " + register.Match.TimeLimit +
                "ms by " + (time - register.Match.TimeLimit) + "ms on the invoke of " + method + ".";
        }

        /// <summary>
        /// Gets the time taken by the <see cref="ControllerEvent.Register"/> in milliseconds.
        /// </summary>
        public int TimeTaken
        {
            get
            {
                return time;
            }
        }

        /// <summary>
        /// Gets a string identifying the method call made to a <see cref="Controller"/> through the
        /// associated <see cref="ControllerEvent.Register"/>.
        /// </summary>
        public string Method
        {
            get
            {
                return methodName;
            }
        }
    }
}