using MBC.Core.Rounds;
using MBC.Shared;

namespace MBC.Core.Events
{
    /// <summary>
    /// Provides information about a <see cref="ControllerRegister"/> that had taken too long to return from
    /// a method call in its associating <see cref="Controller"/>.
    /// </summary>
    public class ControllerTimeoutEvent : ControllerEvent
    {
        /// <summary>
        /// Stores the information provided by the <paramref name="exception"/> and bases the <see cref="Event.Message"/>
        /// from it.
        /// </summary>
        /// <param name="exception">The <see cref="ControllerTimeoutException"/> generated by a <see cref="ControllerUser"/>.</param>
        public ControllerTimeoutEvent(Round rnd, ControllerTimeoutException exception)
            : base(rnd, exception.Register.ID)
        {
            Init(exception.Register, exception.TimeTaken, exception.MethodName);
        }

        /// <summary>
        /// Gets a string identifying the method call made to a <see cref="Controller"/> through the
        /// associated <see cref="ControllerEvent.Register"/>.
        /// </summary>
        public string Method
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the time taken by the <see cref="ControllerEvent.Register"/> in milliseconds.
        /// </summary>
        public int TimeTaken
        {
            get;
            private set;
        }

        private void Init(ControllerRegister register, int time, string method)
        {
            TimeTaken = time;
            Method = method;

            Message = register + " went over the time limit of " + register.Match.TimeLimit +
                "ms by " + (time - register.Match.TimeLimit) + "ms on the invoke of " + method + ".";
        }
    }
}