using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MBC.Core.Events
{
    /// <summary>
    /// A delegate defining a method to invoke with the originating Round object and the Event generated from it.
    /// </summary>
    /// <param name="ev">The Event.</param>
    /// <param name="round">The Round the Event originated from.</param>
    public delegate void MBCEventHandler(Event ev);

    /// <summary>
    /// An Event class is the base class for an MBC-specific event. It provides a message of the event that has
    /// been fired.
    /// </summary>
    public abstract class Event
    {
        protected string message;

        /// <summary>
        /// The message generated by this Event.
        /// </summary>
        public string Message
        {
            get
            {
                return message;
            }
        }
    }
}
