using System.Runtime.Serialization;
using MBC.Core.Threading;
using MBC.Shared;

namespace MBC.Core.Events
{
    /// <summary>
    /// Provides information about a <see cref="Register"/> that had taken too long to return from
    /// a method call in its associating <see cref="Controller"/>.
    /// </summary>
    public class PlayerTimeoutEvent : PlayerEvent
    {
        /// <summary>
        /// Stores the information provided by the <paramref name="exception"/> and bases the <see cref="Event.Message"/>
        /// from it.
        /// </summary>
        /// <param name="exception">The <see cref="ControllerTimeoutException"/> generated by a <see cref="Player"/>.</param>
        public PlayerTimeoutEvent(IDNumber playerID, MethodTimeoutException exception)
            : base(playerID)
        {
            TimeTaken = exception.TimeTaken;
            Method = exception.MethodName;
        }

        public PlayerTimeoutEvent(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }

        /// <summary>
        /// Gets a string identifying the method call made to a <see cref="Controller"/> through the
        /// associated <see cref="PlayerEvent.Register"/>.
        /// </summary>
        public string Method
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the time taken by the <see cref="PlayerEvent.Register"/> in milliseconds.
        /// </summary>
        public int TimeTaken
        {
            get;
            private set;
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            base.GetObjectData(info, context);
        }
    }
}